# fly.toml app configuration file generated for lichess-bot on 2024-08-27T00:09:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lichess-bot'
primary_region = 'lax'

[build]

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
